print("Python is really a great language,", "isn't it?")
str = str(input("Enter your input: "))
print("Received input is : ", str)
str = input("Enter your input: ")
print("Received input is : ", str)
